# Welcome to Jekyll!

title: st1s.io
email: hi@st1s.io
description: > 
  Javascript Software Engineer that is working with Angular, Node, Html5, CSS, Firebase, Mongo.db and all that involves open source culture.
baseurl: "" # the subpath of your site, e.g. /blog
#url: "https://st1s.io" # the base hostname & protocol for your site
url: "http://localhost:4000" # the base hostname & protocol for your site
disqus: 'st1s'

# Social
github: "https://github.com/st1s"
google: "https://plus.google.com/+StewanPacheco"
facebook: "https://facebook.com/StewanPacheco"
twitter:  "https://twitter.com/StewanPacheco"
            
# Build settings
markdown: kramdown
theme: minima

paginate: 8

gems:
  - jekyll-paginate

colors:
  - category: "angularjs"
    colorClass: "is-danger"
    name: "angular.js"
    
  - category: "node"
    colorClass: "is-success"
    name: "node.js"

  - category: "howto"
    colorClass: "is-warning is-bold"
    name: "how-to"

  - category: "community"
    colorClass: "is-info"
    name: "community"

  - category: "test"
    colorClass: "is-primary"
    name: "unit test"

  - category: "github"
    colorClass: "is-dark"
    name: "github"

typingStrings: [
                    "Hi!",
                    "my name is Stewan",
                    "but some people call me ' ist one s '",
                    "do not ask me why O.o",
                    "I like to code",
                    "design",
                    "user experience",
                    "think differently",
                    "build incredible things",
                    "coffee",
                    "solve problems",
                    "coffee",
                    "automate tasks",
                    "did i say coffee?",
                    "...",
                    "I'm currently",
                    "hard working with",
                    "angular",
                    "node",
                    "html5",
                    "css",
                    "firebase",
                    "mongo.db",
                    "all involving",
                    "open source culture",
                    "and s2 javascript",
                    "Thanks for reading",
                    "if you liked",
                    "follow me",
                    "and keep up to date",
                    "(#"
                ]