# Welcome to Jekyll!

title: st1s.io
email: hi@st1s.io
description: > 
  Javascript Software Engineer that works with angular, node, html5, css, firebase, mongo.db and all involving open source culture.
baseurl: "" # the subpath of your site, e.g. /blog
#url: "https://st1s.io" # the base hostname & protocol for your site
url: "http://localhost:4000" # the base hostname & protocol for your site
twitter: st1s
github: st1s

# Build settings
markdown: kramdown
theme: minima

paginate: 8

gems:
  - jekyll-paginate

colors:
  - category: "angularjs"
    colorClass: "is-danger"
    name: "angular.js"
    
  - category: "node"
    colorClass: "is-success"
    name: "node.js"

  - category: "howto"
    colorClass: "is-warning is-bold"
    name: "how-to"

  - category: "community"
    colorClass: "is-info"
    name: "community"

  - category: "test"
    colorClass: "is-primary"
    name: "unit test"

  - category: "github"
    colorClass: "is-dark"
    name: "github"